fix Test_vofile - problem probably introduced in 2cd3e20506e0
The Test_vofile test was failing with:

======================================================================
ERROR: test_multiple_urls (__main__.TestVOFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "vos/test/Test_vofile.py", line 160, in test_multiple_urls
    assert(vofile.url == transferURLs[2])
IndexError: list index out of range

----------------------------------------------------------------------

The readon is that the reference URL list was getting modified, and
this seems to be behaviour (probably bad) that was introduced in
2cd3e20506e0.

Now ensure that the VOFile constructor makes a copy of the
caller's URL list.